### ISSUE TITLE
Not working in Lightning as of 4/17/2020

### ISSUE THREAD

**Issue by kyunussov** [ChenZaichuang/salesforce_show_api_name#1]
Works fine in Classic, but when I click the button in Lightning, nothing happens.  
Tested in orgs with and without Custom Domain (myDomain). 
Just installed the extension for the first time on 4/17/2020, don't know when it stopped working originally.

Chrome version - 80 and 81
SFDC version - Spring '20

**Comment by ChenZaichuang** [comment]
Hi Kyunussov,


Thanks for your feedback, I tried it in lightning just now, it works fine both in uat and production, I guess the reason why it does not work on your side is because of the css difference on the lightning page cause the extension need to locate the field position by css. It will help me to fix it if you can provide username and password of a test sandbox with some test data, the login duration can be limited to less than 2 hours. Or I have no method to know what exactly happened on your side.


I will appreciate if you can provide the test sandbox so that I can fix it as soon as possible.


Thanks
Chen Zaichuang











------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"kyunussov"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月17日(星期五) 晚上11:44
收件人:&nbsp;"ChenZaichuang/salesforce_show_api_name"<salesforce_show_api_name@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ChenZaichuang/salesforce_show_api_name] Not working in Lightning as of 4/17/2020 (#1)





 
Works fine in Classic, but when I click the button in Lightning, nothing happens.
 Tested in orgs with and without Custom Domain (myDomain).
 Just installed the extension for the first time on 4/17/2020, don't know when it stopped working originally.
 
Chrome version - 80 and 81
 SFDC version - Spring '20

**Comment by mhousaini** [comment]
Doesn't work for me in an org with no custom domain, but works in an org with a custom domain. Is this to be expected? @ChenZaichuang

**Comment by ChenZaichuang** [comment]
> Doesn't work for me in an org with no custom domain, but works in an org with a custom domain. Is this to be expected? @ChenZaichuang

I really appreciate for your feedback, I have fixed the issue based on your description, the updated extension is under review and should be available in 24 hours

**Comment by ChenZaichuang** [comment]
@ze-better The new version is available now, you can upgrade or reinstall it

**Comment by ChenZaichuang** [comment]
@kyunussov You can also a try to see whether it works in lightning in your salesforce environment.

**Comment by mhousaini** [comment]
Thanks @ChenZaichuang! The update seems to have fixed the issue.
